Wutnu3/Areas/Manage/Controllers/ErrorLogController.cs
using System.Web.Mvc;
using Wutnu.Common;
using Wutnu.Data;
using Wutnu.Infrastructure;

namespace Wutnu.Areas.Manage.Controllers
{
    [Authorize(Roles = WutRoles.WutNuAdmins)]
    public class ErrorLogController : BaseController
    {
        public ErrorLogController(WutCache cache, WutNuContext models)
            :base(cache, models)
        {
        }

        public ActionResult Index()
        {
            ViewBag.SiteName = "Wut Admin";
            return View();
        }
    }
}

Wutnu3/Views/Shared/_Layout.cshtml
@using Wutnu.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Wut?</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("styles", required:false)
    <meta name="description" content="An Azure demo site" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Wut?", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new {})</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Manage", "Index", "Home", new { area = "Manage" }, new {})</li>
                        if (User.IsInRole(WutRoles.WutNuAdmins))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Error Logs", "Index", "ErrorLog", new { area = "Manage" }, new { })</li>
                                </ul>
                            </li>
                        }
                    }
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new {})</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer class="bg-4">
            <div class="container">
                <p>&copy; @DateTime.Now.Year - Wut.nu (Wut?)</p>
                <p>View the project: <a href="https://github.com/bretthacker/Wutnu" target="_blank">https://github.com/bretthacker/Wutnu</a></p>
            </div>
        </footer>

    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>